# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.25.0"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = ""
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    build_number = latest_hockeyapp_version_number(
       api_token: "",
       app_name: "Indigo POS",
       platform: 'Android',
       release_type: '2' # 0 = Beta (default), 1 = Store, 2 = Alpha, 3 = Enterprise"
    )

    path = '../app/build.gradle'
    re = /versionCode\s+(\d+)/

    s = File.read(path)
    s[re, 1] = (build_number + 1).to_s

    f = File.new(path, 'w')
    f.write(s)
    f.close

    gradle(task: "assembleRelease")
    # crashlytics

    # Push to Hockey
    hockey(api_token: "")
    #sh "fastlane bump_version_code"
  end

  lane :bump_version_code do
    path = '../app/build.gradle'
    re = /versionCode\s+(\d+)/

    s = File.read(path)
    versionCode = s[re, 1].to_i
    s[re, 1] = (versionCode + 1).to_s

    f = File.new(path, 'w')
    f.write(s)
    f.close
  end

  lane :latest_hockeyapp_version_number do
    latest_hockeyapp_version_number(
       api_token: "",
       app_name: "Indigo POS",
       platform: 'Android',
       release_type: '2' # 0 = Beta (default), 1 = Store, 2 = Alpha, 3 = Enterprise"
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    supply
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    if lane_context[SharedValues::HOCKEY_DOWNLOAD_LINK]
      slack(
        message: "Successfully deployed new App Update. Build link: " + lane_context[SharedValues::HOCKEY_DOWNLOAD_LINK]
      )
    end
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer
